/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d0088f10-4607-41bf-b965-2e9e508cb391",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rOW5uZUiV",
    "aws_user_pools_web_client_id": "3rjp6ua2bkd7ajrgf373loeujh",
    "oauth": {}
};


export default awsmobile;
